//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#pragma warning disable 108 // Disable "CS0108 '{derivedDto}.ToJson()' hides inherited member '{dtoBase}.ToJson()'. Use the new keyword if hiding was intended."
#pragma warning disable 114 // Disable "CS0114 '{derivedDto}.RaisePropertyChanged(String)' hides inherited member 'dtoBase.RaisePropertyChanged(String)'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword."
#pragma warning disable 472 // Disable "CS0472 The result of the expression is always 'false' since a value of type 'Int32' is never equal to 'null' of type 'Int32?'
#pragma warning disable 612 // Disable "CS0612 '...' is obsolete"
#pragma warning disable 649 // Disable "CS0649 Field is never assigned to, and will always have its default value null"
#pragma warning disable 1573 // Disable "CS1573 Parameter '...' has no matching param tag in the XML comment for ...
#pragma warning disable 1591 // Disable "CS1591 Missing XML comment for publicly visible type or member ..."
#pragma warning disable 8073 // Disable "CS8073 The result of the expression is always 'false' since a value of type 'T' is never equal to 'null' of type 'T?'"
#pragma warning disable 3016 // Disable "CS3016 Arrays as attribute arguments is not CLS-compliant"
#pragma warning disable 8600 // Disable "CS8600 Converting null literal or possible null value to non-nullable type"
#pragma warning disable 8602 // Disable "CS8602 Dereference of a possibly null reference"
#pragma warning disable 8603 // Disable "CS8603 Possible null reference return"
#pragma warning disable 8604 // Disable "CS8604 Possible null reference argument for parameter"
#pragma warning disable 8625 // Disable "CS8625 Cannot convert null literal to non-nullable reference type"
#pragma warning disable 8765 // Disable "CS8765 Nullability of type of parameter doesn't match overridden member (possibly because of nullability attributes)."

namespace WeatherApi.Client
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial interface IWeatherClient
    {

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Current weather (JSON)
        /// </summary>
        /// <returns>Successful response</returns>
        /// <exception cref="WeatherApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<GetCurrentResponse> GetCurrentAsync(GetCurrentRequest getCurrentRequest, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Forecast (JSON)
        /// </summary>
        /// <returns>Successful response</returns>
        /// <exception cref="WeatherApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<GetForecastResponse> GetForecastAsync(GetForecastRequest getForecastRequest, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Historical weather (JSON)
        /// </summary>
        /// <returns>Successful response</returns>
        /// <exception cref="WeatherApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<GetHistoryResponse> GetHistoryAsync(GetHistoryRequest getHistoryRequest, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Weather alerts (JSON)
        /// </summary>
        /// <remarks>
        /// ## Weather Alerts
        /// <br/>
        /// <br/>Retrieves active weather alerts and warnings for a specified location. Get real-time severe weather notifications issued by meteorological agencies.
        /// <br/>
        /// <br/>{{baseUrl}}/alerts.json?q=string
        /// <br/>
        /// <br/>### Required Parameters
        /// <br/>
        /// <br/>- **q** (query): Location identifier - can be:
        /// <br/>    
        /// <br/>    - City name (e.g., "Miami")
        /// <br/>        
        /// <br/>    - Latitude/longitude (e.g., "25.7617,-80.1918")
        /// <br/>        
        /// <br/>    - US zip code (e.g., "33101")
        /// <br/>        
        /// <br/>    - UK postcode (e.g., "SW1")
        /// <br/>        
        /// <br/>    - IP address (e.g., "100.0.0.1")
        /// <br/>        
        /// <br/>    - IATA airport code (e.g., "MIA")
        /// <br/>        
        /// <br/>- **key** (query): Your WeatherAPI.com API key for authentication
        /// <br/>    
        /// <br/>
        /// <br/>### Optional Parameters
        /// <br/>
        /// <br/>None for this endpoint
        /// <br/>
        /// <br/>### Common Use Cases
        /// <br/>
        /// <br/>- Emergency weather notification systems
        /// <br/>    
        /// <br/>- Travel safety alerts
        /// <br/>    
        /// <br/>- Event planning risk assessment
        /// <br/>    
        /// <br/>- Public safety applications
        /// <br/>    
        /// <br/>- Weather-dependent business operations monitoring
        /// <br/>    
        /// <br/>- Mobile app push notifications for severe weather
        /// <br/>    
        /// <br/>
        /// <br/>### Response Highlights
        /// <br/>
        /// <br/>Returns active weather alerts including:
        /// <br/>
        /// <br/>- Alert type and severity level
        /// <br/>    
        /// <br/>- Headline and detailed description
        /// <br/>    
        /// <br/>- Effective and expiration times
        /// <br/>    
        /// <br/>- Affected areas
        /// <br/>    
        /// <br/>- Instructions and recommendations
        /// <br/>    
        /// <br/>- Issuing meteorological authority
        /// <br/>    
        /// <br/>
        /// <br/>Alerts may include warnings for hurricanes, tornadoes, floods, heat waves, winter storms, and other severe weather conditions.
        /// </remarks>
        /// <returns>Successful response</returns>
        /// <exception cref="WeatherApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<GetAlertsResponse> GetAlertsAsync(GetAlertsRequest getAlertsRequest, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

    }

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    internal partial class WeatherClient : IWeatherClient
    {
        private System.Net.Http.HttpClient _httpClient;
        private static System.Lazy<System.Text.Json.JsonSerializerOptions> _settings = new System.Lazy<System.Text.Json.JsonSerializerOptions>(CreateSerializerSettings, true);
        private System.Text.Json.JsonSerializerOptions _instanceSettings;

    #pragma warning disable CS8618 // Non-nullable field must contain a non-null value when exiting constructor. Consider declaring as nullable.
        public WeatherClient(System.Net.Http.HttpClient httpClient)
    #pragma warning restore CS8618 // Non-nullable field must contain a non-null value when exiting constructor. Consider declaring as nullable.
        {
            _httpClient = httpClient;
            Initialize();
        }

        private static System.Text.Json.JsonSerializerOptions CreateSerializerSettings()
        {
            var settings = new System.Text.Json.JsonSerializerOptions();
            UpdateJsonSerializerSettings(settings);
            return settings;
        }

        protected System.Text.Json.JsonSerializerOptions JsonSerializerSettings { get { return _instanceSettings ?? _settings.Value; } }

        static partial void UpdateJsonSerializerSettings(System.Text.Json.JsonSerializerOptions settings);

        partial void Initialize();

        partial void PrepareRequest(System.Net.Http.HttpClient client, System.Net.Http.HttpRequestMessage request, string url);
        partial void PrepareRequest(System.Net.Http.HttpClient client, System.Net.Http.HttpRequestMessage request, System.Text.StringBuilder urlBuilder);
        partial void ProcessResponse(System.Net.Http.HttpClient client, System.Net.Http.HttpResponseMessage response);

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Current weather (JSON)
        /// </summary>
        /// <returns>Successful response</returns>
        /// <exception cref="WeatherApiException">A server side error occurred.</exception>
        public virtual async System.Threading.Tasks.Task<GetCurrentResponse> GetCurrentAsync(GetCurrentRequest getCurrentRequest, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            if (getCurrentRequest == null)
                throw new System.ArgumentNullException("getCurrentRequest");

            var client_ = _httpClient;
            var disposeClient_ = false;
            try
            {
                using (var request_ = new System.Net.Http.HttpRequestMessage())
                {
                    request_.Method = new System.Net.Http.HttpMethod("GET");
                    request_.Headers.Accept.Add(System.Net.Http.Headers.MediaTypeWithQualityHeaderValue.Parse("application/json"));

                    var urlBuilder_ = new System.Text.StringBuilder();
                
                    // Operation Path: "v1/current.json"
                    urlBuilder_.Append("v1/current.json");
                    urlBuilder_.Append('?');
                    if (getCurrentRequest.Q != null)
                    {
                        urlBuilder_.Append(System.Uri.EscapeDataString("q")).Append('=').Append(System.Uri.EscapeDataString(ConvertToString(getCurrentRequest.Q, System.Globalization.CultureInfo.InvariantCulture))).Append('&');
                    }
                    if (getCurrentRequest.Aqi != null)
                    {
                        urlBuilder_.Append(System.Uri.EscapeDataString("aqi")).Append('=').Append(System.Uri.EscapeDataString(ConvertToString(getCurrentRequest.Aqi, System.Globalization.CultureInfo.InvariantCulture))).Append('&');
                    }
                    if (getCurrentRequest.Pollen != null)
                    {
                        urlBuilder_.Append(System.Uri.EscapeDataString("pollen")).Append('=').Append(System.Uri.EscapeDataString(ConvertToString(getCurrentRequest.Pollen, System.Globalization.CultureInfo.InvariantCulture))).Append('&');
                    }
                    if (getCurrentRequest.Lang != null)
                    {
                        urlBuilder_.Append(System.Uri.EscapeDataString("lang")).Append('=').Append(System.Uri.EscapeDataString(ConvertToString(getCurrentRequest.Lang, System.Globalization.CultureInfo.InvariantCulture))).Append('&');
                    }
                    if (getCurrentRequest.Current_fields != null)
                    {
                        urlBuilder_.Append(System.Uri.EscapeDataString("current_fields")).Append('=').Append(System.Uri.EscapeDataString(ConvertToString(getCurrentRequest.Current_fields, System.Globalization.CultureInfo.InvariantCulture))).Append('&');
                    }
                    urlBuilder_.Length--;

                    PrepareRequest(client_, request_, urlBuilder_);

                    var url_ = urlBuilder_.ToString();
                    request_.RequestUri = new System.Uri(url_, System.UriKind.RelativeOrAbsolute);

                    PrepareRequest(client_, request_, url_);

                    var response_ = await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
                    var disposeResponse_ = true;
                    try
                    {
                        var headers_ = new System.Collections.Generic.Dictionary<string, System.Collections.Generic.IEnumerable<string>>();
                        foreach (var item_ in response_.Headers)
                            headers_[item_.Key] = item_.Value;
                        if (response_.Content != null && response_.Content.Headers != null)
                        {
                            foreach (var item_ in response_.Content.Headers)
                                headers_[item_.Key] = item_.Value;
                        }

                        ProcessResponse(client_, response_);

                        var status_ = (int)response_.StatusCode;
                        if (status_ == 200)
                        {
                            var objectResponse_ = await ReadObjectResponseAsync<GetCurrentResponse>(response_, headers_, cancellationToken).ConfigureAwait(false);
                            if (objectResponse_.Object == null)
                            {
                                throw new WeatherApiException("Response was null which was not expected.", status_, objectResponse_.Text, headers_, null);
                            }
                            return objectResponse_.Object;
                        }
                        else
                        {
                            var responseData_ = response_.Content == null ? null : await ReadAsStringAsync(response_.Content, cancellationToken).ConfigureAwait(false);
                            throw new WeatherApiException("The HTTP status code of the response was not expected (" + status_ + ").", status_, responseData_, headers_, null);
                        }
                    }
                    finally
                    {
                        if (disposeResponse_)
                            response_.Dispose();
                    }
                }
            }
            finally
            {
                if (disposeClient_)
                    client_.Dispose();
            }
        }

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Forecast (JSON)
        /// </summary>
        /// <returns>Successful response</returns>
        /// <exception cref="WeatherApiException">A server side error occurred.</exception>
        public virtual async System.Threading.Tasks.Task<GetForecastResponse> GetForecastAsync(GetForecastRequest getForecastRequest, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            if (getForecastRequest == null)
                throw new System.ArgumentNullException("getForecastRequest");

            var client_ = _httpClient;
            var disposeClient_ = false;
            try
            {
                using (var request_ = new System.Net.Http.HttpRequestMessage())
                {
                    request_.Method = new System.Net.Http.HttpMethod("GET");
                    request_.Headers.Accept.Add(System.Net.Http.Headers.MediaTypeWithQualityHeaderValue.Parse("application/json"));

                    var urlBuilder_ = new System.Text.StringBuilder();
                
                    // Operation Path: "v1/forecast.json"
                    urlBuilder_.Append("v1/forecast.json");
                    urlBuilder_.Append('?');
                    if (getForecastRequest.Q != null)
                    {
                        urlBuilder_.Append(System.Uri.EscapeDataString("q")).Append('=').Append(System.Uri.EscapeDataString(ConvertToString(getForecastRequest.Q, System.Globalization.CultureInfo.InvariantCulture))).Append('&');
                    }
                    if (getForecastRequest.Days != null)
                    {
                        urlBuilder_.Append(System.Uri.EscapeDataString("days")).Append('=').Append(System.Uri.EscapeDataString(ConvertToString(getForecastRequest.Days, System.Globalization.CultureInfo.InvariantCulture))).Append('&');
                    }
                    if (getForecastRequest.Dt != null)
                    {
                        urlBuilder_.Append(System.Uri.EscapeDataString("dt")).Append('=').Append(System.Uri.EscapeDataString(ConvertToString(getForecastRequest.Dt, System.Globalization.CultureInfo.InvariantCulture))).Append('&');
                    }
                    if (getForecastRequest.Unixdt != null)
                    {
                        urlBuilder_.Append(System.Uri.EscapeDataString("unixdt")).Append('=').Append(System.Uri.EscapeDataString(ConvertToString(getForecastRequest.Unixdt, System.Globalization.CultureInfo.InvariantCulture))).Append('&');
                    }
                    if (getForecastRequest.Hour != null)
                    {
                        urlBuilder_.Append(System.Uri.EscapeDataString("hour")).Append('=').Append(System.Uri.EscapeDataString(ConvertToString(getForecastRequest.Hour, System.Globalization.CultureInfo.InvariantCulture))).Append('&');
                    }
                    if (getForecastRequest.Alerts != null)
                    {
                        urlBuilder_.Append(System.Uri.EscapeDataString("alerts")).Append('=').Append(System.Uri.EscapeDataString(ConvertToString(getForecastRequest.Alerts, System.Globalization.CultureInfo.InvariantCulture))).Append('&');
                    }
                    if (getForecastRequest.Aqi != null)
                    {
                        urlBuilder_.Append(System.Uri.EscapeDataString("aqi")).Append('=').Append(System.Uri.EscapeDataString(ConvertToString(getForecastRequest.Aqi, System.Globalization.CultureInfo.InvariantCulture))).Append('&');
                    }
                    if (getForecastRequest.Pollen != null)
                    {
                        urlBuilder_.Append(System.Uri.EscapeDataString("pollen")).Append('=').Append(System.Uri.EscapeDataString(ConvertToString(getForecastRequest.Pollen, System.Globalization.CultureInfo.InvariantCulture))).Append('&');
                    }
                    if (getForecastRequest.Tp != null)
                    {
                        urlBuilder_.Append(System.Uri.EscapeDataString("tp")).Append('=').Append(System.Uri.EscapeDataString(ConvertToString(getForecastRequest.Tp, System.Globalization.CultureInfo.InvariantCulture))).Append('&');
                    }
                    if (getForecastRequest.Current_fields != null)
                    {
                        urlBuilder_.Append(System.Uri.EscapeDataString("current_fields")).Append('=').Append(System.Uri.EscapeDataString(ConvertToString(getForecastRequest.Current_fields, System.Globalization.CultureInfo.InvariantCulture))).Append('&');
                    }
                    if (getForecastRequest.Day_fields != null)
                    {
                        urlBuilder_.Append(System.Uri.EscapeDataString("day_fields")).Append('=').Append(System.Uri.EscapeDataString(ConvertToString(getForecastRequest.Day_fields, System.Globalization.CultureInfo.InvariantCulture))).Append('&');
                    }
                    if (getForecastRequest.Hour_fields != null)
                    {
                        urlBuilder_.Append(System.Uri.EscapeDataString("hour_fields")).Append('=').Append(System.Uri.EscapeDataString(ConvertToString(getForecastRequest.Hour_fields, System.Globalization.CultureInfo.InvariantCulture))).Append('&');
                    }
                    if (getForecastRequest.Et0 != null)
                    {
                        urlBuilder_.Append(System.Uri.EscapeDataString("et0")).Append('=').Append(System.Uri.EscapeDataString(ConvertToString(getForecastRequest.Et0, System.Globalization.CultureInfo.InvariantCulture))).Append('&');
                    }
                    if (getForecastRequest.Lang != null)
                    {
                        urlBuilder_.Append(System.Uri.EscapeDataString("lang")).Append('=').Append(System.Uri.EscapeDataString(ConvertToString(getForecastRequest.Lang, System.Globalization.CultureInfo.InvariantCulture))).Append('&');
                    }
                    urlBuilder_.Length--;

                    PrepareRequest(client_, request_, urlBuilder_);

                    var url_ = urlBuilder_.ToString();
                    request_.RequestUri = new System.Uri(url_, System.UriKind.RelativeOrAbsolute);

                    PrepareRequest(client_, request_, url_);

                    var response_ = await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
                    var disposeResponse_ = true;
                    try
                    {
                        var headers_ = new System.Collections.Generic.Dictionary<string, System.Collections.Generic.IEnumerable<string>>();
                        foreach (var item_ in response_.Headers)
                            headers_[item_.Key] = item_.Value;
                        if (response_.Content != null && response_.Content.Headers != null)
                        {
                            foreach (var item_ in response_.Content.Headers)
                                headers_[item_.Key] = item_.Value;
                        }

                        ProcessResponse(client_, response_);

                        var status_ = (int)response_.StatusCode;
                        if (status_ == 200)
                        {
                            var objectResponse_ = await ReadObjectResponseAsync<GetForecastResponse>(response_, headers_, cancellationToken).ConfigureAwait(false);
                            if (objectResponse_.Object == null)
                            {
                                throw new WeatherApiException("Response was null which was not expected.", status_, objectResponse_.Text, headers_, null);
                            }
                            return objectResponse_.Object;
                        }
                        else
                        {
                            var responseData_ = response_.Content == null ? null : await ReadAsStringAsync(response_.Content, cancellationToken).ConfigureAwait(false);
                            throw new WeatherApiException("The HTTP status code of the response was not expected (" + status_ + ").", status_, responseData_, headers_, null);
                        }
                    }
                    finally
                    {
                        if (disposeResponse_)
                            response_.Dispose();
                    }
                }
            }
            finally
            {
                if (disposeClient_)
                    client_.Dispose();
            }
        }

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Historical weather (JSON)
        /// </summary>
        /// <returns>Successful response</returns>
        /// <exception cref="WeatherApiException">A server side error occurred.</exception>
        public virtual async System.Threading.Tasks.Task<GetHistoryResponse> GetHistoryAsync(GetHistoryRequest getHistoryRequest, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            if (getHistoryRequest == null)
                throw new System.ArgumentNullException("getHistoryRequest");

            var client_ = _httpClient;
            var disposeClient_ = false;
            try
            {
                using (var request_ = new System.Net.Http.HttpRequestMessage())
                {
                    request_.Method = new System.Net.Http.HttpMethod("GET");
                    request_.Headers.Accept.Add(System.Net.Http.Headers.MediaTypeWithQualityHeaderValue.Parse("application/json"));

                    var urlBuilder_ = new System.Text.StringBuilder();
                
                    // Operation Path: "v1/history.json"
                    urlBuilder_.Append("v1/history.json");
                    urlBuilder_.Append('?');
                    if (getHistoryRequest.Q != null)
                    {
                        urlBuilder_.Append(System.Uri.EscapeDataString("q")).Append('=').Append(System.Uri.EscapeDataString(ConvertToString(getHistoryRequest.Q, System.Globalization.CultureInfo.InvariantCulture))).Append('&');
                    }
                    if (getHistoryRequest.Dt != null)
                    {
                        urlBuilder_.Append(System.Uri.EscapeDataString("dt")).Append('=').Append(System.Uri.EscapeDataString(ConvertToString(getHistoryRequest.Dt, System.Globalization.CultureInfo.InvariantCulture))).Append('&');
                    }
                    if (getHistoryRequest.Unixdt != null)
                    {
                        urlBuilder_.Append(System.Uri.EscapeDataString("unixdt")).Append('=').Append(System.Uri.EscapeDataString(ConvertToString(getHistoryRequest.Unixdt, System.Globalization.CultureInfo.InvariantCulture))).Append('&');
                    }
                    if (getHistoryRequest.End_dt != null)
                    {
                        urlBuilder_.Append(System.Uri.EscapeDataString("end_dt")).Append('=').Append(System.Uri.EscapeDataString(ConvertToString(getHistoryRequest.End_dt, System.Globalization.CultureInfo.InvariantCulture))).Append('&');
                    }
                    if (getHistoryRequest.Unixend_dt != null)
                    {
                        urlBuilder_.Append(System.Uri.EscapeDataString("unixend_dt")).Append('=').Append(System.Uri.EscapeDataString(ConvertToString(getHistoryRequest.Unixend_dt, System.Globalization.CultureInfo.InvariantCulture))).Append('&');
                    }
                    if (getHistoryRequest.Hour != null)
                    {
                        urlBuilder_.Append(System.Uri.EscapeDataString("hour")).Append('=').Append(System.Uri.EscapeDataString(ConvertToString(getHistoryRequest.Hour, System.Globalization.CultureInfo.InvariantCulture))).Append('&');
                    }
                    if (getHistoryRequest.Aqi != null)
                    {
                        urlBuilder_.Append(System.Uri.EscapeDataString("aqi")).Append('=').Append(System.Uri.EscapeDataString(ConvertToString(getHistoryRequest.Aqi, System.Globalization.CultureInfo.InvariantCulture))).Append('&');
                    }
                    if (getHistoryRequest.Pollen != null)
                    {
                        urlBuilder_.Append(System.Uri.EscapeDataString("pollen")).Append('=').Append(System.Uri.EscapeDataString(ConvertToString(getHistoryRequest.Pollen, System.Globalization.CultureInfo.InvariantCulture))).Append('&');
                    }
                    if (getHistoryRequest.Tp != null)
                    {
                        urlBuilder_.Append(System.Uri.EscapeDataString("tp")).Append('=').Append(System.Uri.EscapeDataString(ConvertToString(getHistoryRequest.Tp, System.Globalization.CultureInfo.InvariantCulture))).Append('&');
                    }
                    if (getHistoryRequest.Current_fields != null)
                    {
                        urlBuilder_.Append(System.Uri.EscapeDataString("current_fields")).Append('=').Append(System.Uri.EscapeDataString(ConvertToString(getHistoryRequest.Current_fields, System.Globalization.CultureInfo.InvariantCulture))).Append('&');
                    }
                    if (getHistoryRequest.Day_fields != null)
                    {
                        urlBuilder_.Append(System.Uri.EscapeDataString("day_fields")).Append('=').Append(System.Uri.EscapeDataString(ConvertToString(getHistoryRequest.Day_fields, System.Globalization.CultureInfo.InvariantCulture))).Append('&');
                    }
                    if (getHistoryRequest.Hour_fields != null)
                    {
                        urlBuilder_.Append(System.Uri.EscapeDataString("hour_fields")).Append('=').Append(System.Uri.EscapeDataString(ConvertToString(getHistoryRequest.Hour_fields, System.Globalization.CultureInfo.InvariantCulture))).Append('&');
                    }
                    if (getHistoryRequest.Solar != null)
                    {
                        urlBuilder_.Append(System.Uri.EscapeDataString("solar")).Append('=').Append(System.Uri.EscapeDataString(ConvertToString(getHistoryRequest.Solar, System.Globalization.CultureInfo.InvariantCulture))).Append('&');
                    }
                    if (getHistoryRequest.Et0 != null)
                    {
                        urlBuilder_.Append(System.Uri.EscapeDataString("et0")).Append('=').Append(System.Uri.EscapeDataString(ConvertToString(getHistoryRequest.Et0, System.Globalization.CultureInfo.InvariantCulture))).Append('&');
                    }
                    if (getHistoryRequest.Wind100mph != null)
                    {
                        urlBuilder_.Append(System.Uri.EscapeDataString("wind100mph")).Append('=').Append(System.Uri.EscapeDataString(ConvertToString(getHistoryRequest.Wind100mph, System.Globalization.CultureInfo.InvariantCulture))).Append('&');
                    }
                    if (getHistoryRequest.Wind100kph != null)
                    {
                        urlBuilder_.Append(System.Uri.EscapeDataString("wind100kph")).Append('=').Append(System.Uri.EscapeDataString(ConvertToString(getHistoryRequest.Wind100kph, System.Globalization.CultureInfo.InvariantCulture))).Append('&');
                    }
                    if (getHistoryRequest.Lang != null)
                    {
                        urlBuilder_.Append(System.Uri.EscapeDataString("lang")).Append('=').Append(System.Uri.EscapeDataString(ConvertToString(getHistoryRequest.Lang, System.Globalization.CultureInfo.InvariantCulture))).Append('&');
                    }
                    urlBuilder_.Length--;

                    PrepareRequest(client_, request_, urlBuilder_);

                    var url_ = urlBuilder_.ToString();
                    request_.RequestUri = new System.Uri(url_, System.UriKind.RelativeOrAbsolute);

                    PrepareRequest(client_, request_, url_);

                    var response_ = await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
                    var disposeResponse_ = true;
                    try
                    {
                        var headers_ = new System.Collections.Generic.Dictionary<string, System.Collections.Generic.IEnumerable<string>>();
                        foreach (var item_ in response_.Headers)
                            headers_[item_.Key] = item_.Value;
                        if (response_.Content != null && response_.Content.Headers != null)
                        {
                            foreach (var item_ in response_.Content.Headers)
                                headers_[item_.Key] = item_.Value;
                        }

                        ProcessResponse(client_, response_);

                        var status_ = (int)response_.StatusCode;
                        if (status_ == 200)
                        {
                            var objectResponse_ = await ReadObjectResponseAsync<GetHistoryResponse>(response_, headers_, cancellationToken).ConfigureAwait(false);
                            if (objectResponse_.Object == null)
                            {
                                throw new WeatherApiException("Response was null which was not expected.", status_, objectResponse_.Text, headers_, null);
                            }
                            return objectResponse_.Object;
                        }
                        else
                        {
                            var responseData_ = response_.Content == null ? null : await ReadAsStringAsync(response_.Content, cancellationToken).ConfigureAwait(false);
                            throw new WeatherApiException("The HTTP status code of the response was not expected (" + status_ + ").", status_, responseData_, headers_, null);
                        }
                    }
                    finally
                    {
                        if (disposeResponse_)
                            response_.Dispose();
                    }
                }
            }
            finally
            {
                if (disposeClient_)
                    client_.Dispose();
            }
        }

        /// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
        /// <summary>
        /// Weather alerts (JSON)
        /// </summary>
        /// <remarks>
        /// ## Weather Alerts
        /// <br/>
        /// <br/>Retrieves active weather alerts and warnings for a specified location. Get real-time severe weather notifications issued by meteorological agencies.
        /// <br/>
        /// <br/>{{baseUrl}}/alerts.json?q=string
        /// <br/>
        /// <br/>### Required Parameters
        /// <br/>
        /// <br/>- **q** (query): Location identifier - can be:
        /// <br/>    
        /// <br/>    - City name (e.g., "Miami")
        /// <br/>        
        /// <br/>    - Latitude/longitude (e.g., "25.7617,-80.1918")
        /// <br/>        
        /// <br/>    - US zip code (e.g., "33101")
        /// <br/>        
        /// <br/>    - UK postcode (e.g., "SW1")
        /// <br/>        
        /// <br/>    - IP address (e.g., "100.0.0.1")
        /// <br/>        
        /// <br/>    - IATA airport code (e.g., "MIA")
        /// <br/>        
        /// <br/>- **key** (query): Your WeatherAPI.com API key for authentication
        /// <br/>    
        /// <br/>
        /// <br/>### Optional Parameters
        /// <br/>
        /// <br/>None for this endpoint
        /// <br/>
        /// <br/>### Common Use Cases
        /// <br/>
        /// <br/>- Emergency weather notification systems
        /// <br/>    
        /// <br/>- Travel safety alerts
        /// <br/>    
        /// <br/>- Event planning risk assessment
        /// <br/>    
        /// <br/>- Public safety applications
        /// <br/>    
        /// <br/>- Weather-dependent business operations monitoring
        /// <br/>    
        /// <br/>- Mobile app push notifications for severe weather
        /// <br/>    
        /// <br/>
        /// <br/>### Response Highlights
        /// <br/>
        /// <br/>Returns active weather alerts including:
        /// <br/>
        /// <br/>- Alert type and severity level
        /// <br/>    
        /// <br/>- Headline and detailed description
        /// <br/>    
        /// <br/>- Effective and expiration times
        /// <br/>    
        /// <br/>- Affected areas
        /// <br/>    
        /// <br/>- Instructions and recommendations
        /// <br/>    
        /// <br/>- Issuing meteorological authority
        /// <br/>    
        /// <br/>
        /// <br/>Alerts may include warnings for hurricanes, tornadoes, floods, heat waves, winter storms, and other severe weather conditions.
        /// </remarks>
        /// <returns>Successful response</returns>
        /// <exception cref="WeatherApiException">A server side error occurred.</exception>
        public virtual async System.Threading.Tasks.Task<GetAlertsResponse> GetAlertsAsync(GetAlertsRequest getAlertsRequest, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            if (getAlertsRequest == null)
                throw new System.ArgumentNullException("getAlertsRequest");

            var client_ = _httpClient;
            var disposeClient_ = false;
            try
            {
                using (var request_ = new System.Net.Http.HttpRequestMessage())
                {
                    request_.Method = new System.Net.Http.HttpMethod("GET");
                    request_.Headers.Accept.Add(System.Net.Http.Headers.MediaTypeWithQualityHeaderValue.Parse("application/json"));

                    var urlBuilder_ = new System.Text.StringBuilder();
                
                    // Operation Path: "v1/alerts.json"
                    urlBuilder_.Append("v1/alerts.json");
                    urlBuilder_.Append('?');
                    if (getAlertsRequest.Q != null)
                    {
                        urlBuilder_.Append(System.Uri.EscapeDataString("q")).Append('=').Append(System.Uri.EscapeDataString(ConvertToString(getAlertsRequest.Q, System.Globalization.CultureInfo.InvariantCulture))).Append('&');
                    }
                    urlBuilder_.Length--;

                    PrepareRequest(client_, request_, urlBuilder_);

                    var url_ = urlBuilder_.ToString();
                    request_.RequestUri = new System.Uri(url_, System.UriKind.RelativeOrAbsolute);

                    PrepareRequest(client_, request_, url_);

                    var response_ = await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
                    var disposeResponse_ = true;
                    try
                    {
                        var headers_ = new System.Collections.Generic.Dictionary<string, System.Collections.Generic.IEnumerable<string>>();
                        foreach (var item_ in response_.Headers)
                            headers_[item_.Key] = item_.Value;
                        if (response_.Content != null && response_.Content.Headers != null)
                        {
                            foreach (var item_ in response_.Content.Headers)
                                headers_[item_.Key] = item_.Value;
                        }

                        ProcessResponse(client_, response_);

                        var status_ = (int)response_.StatusCode;
                        if (status_ == 200)
                        {
                            var objectResponse_ = await ReadObjectResponseAsync<GetAlertsResponse>(response_, headers_, cancellationToken).ConfigureAwait(false);
                            if (objectResponse_.Object == null)
                            {
                                throw new WeatherApiException("Response was null which was not expected.", status_, objectResponse_.Text, headers_, null);
                            }
                            return objectResponse_.Object;
                        }
                        else
                        {
                            var responseData_ = response_.Content == null ? null : await ReadAsStringAsync(response_.Content, cancellationToken).ConfigureAwait(false);
                            throw new WeatherApiException("The HTTP status code of the response was not expected (" + status_ + ").", status_, responseData_, headers_, null);
                        }
                    }
                    finally
                    {
                        if (disposeResponse_)
                            response_.Dispose();
                    }
                }
            }
            finally
            {
                if (disposeClient_)
                    client_.Dispose();
            }
        }

        protected struct ObjectResponseResult<T>
        {
            public ObjectResponseResult(T responseObject, string responseText)
            {
                this.Object = responseObject;
                this.Text = responseText;
            }

            public T Object { get; }

            public string Text { get; }
        }

        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        private static System.Threading.Tasks.Task<string> ReadAsStringAsync(System.Net.Http.HttpContent content, System.Threading.CancellationToken cancellationToken)
        {
    #if NET5_0_OR_GREATER
            return content.ReadAsStringAsync(cancellationToken);
    #else
            return content.ReadAsStringAsync();
    #endif
        }

        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        private static System.Threading.Tasks.Task<System.IO.Stream> ReadAsStreamAsync(System.Net.Http.HttpContent content, System.Threading.CancellationToken cancellationToken)
        {
    #if NET5_0_OR_GREATER
            return content.ReadAsStreamAsync(cancellationToken);
    #else
            return content.ReadAsStreamAsync();
    #endif
        }

        public bool ReadResponseAsString { get; set; }

        protected virtual async System.Threading.Tasks.Task<ObjectResponseResult<T>> ReadObjectResponseAsync<T>(System.Net.Http.HttpResponseMessage response, System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IEnumerable<string>> headers, System.Threading.CancellationToken cancellationToken)
        {
            if (response == null || response.Content == null)
            {
                return new ObjectResponseResult<T>(default(T), string.Empty);
            }

            if (ReadResponseAsString)
            {
                var responseText = await ReadAsStringAsync(response.Content, cancellationToken).ConfigureAwait(false);
                try
                {
                    var typedBody = System.Text.Json.JsonSerializer.Deserialize<T>(responseText, JsonSerializerSettings);
                    return new ObjectResponseResult<T>(typedBody, responseText);
                }
                catch (System.Text.Json.JsonException exception)
                {
                    var message = "Could not deserialize the response body string as " + typeof(T).FullName + ".";
                    throw new WeatherApiException(message, (int)response.StatusCode, responseText, headers, exception);
                }
            }
            else
            {
                try
                {
                    using (var responseStream = await ReadAsStreamAsync(response.Content, cancellationToken).ConfigureAwait(false))
                    {
                        var typedBody = await System.Text.Json.JsonSerializer.DeserializeAsync<T>(responseStream, JsonSerializerSettings, cancellationToken).ConfigureAwait(false);
                        return new ObjectResponseResult<T>(typedBody, string.Empty);
                    }
                }
                catch (System.Text.Json.JsonException exception)
                {
                    var message = "Could not deserialize the response body stream as " + typeof(T).FullName + ".";
                    throw new WeatherApiException(message, (int)response.StatusCode, string.Empty, headers, exception);
                }
            }
        }

        private string ConvertToString(object value, System.Globalization.CultureInfo cultureInfo)
        {
            if (value == null)
            {
                return "";
            }

            if (value is System.Enum)
            {
                var name = System.Enum.GetName(value.GetType(), value);
                if (name != null)
                {
                    var field_ = System.Reflection.IntrospectionExtensions.GetTypeInfo(value.GetType()).GetDeclaredField(name);
                    if (field_ != null)
                    {
                        var attribute = System.Reflection.CustomAttributeExtensions.GetCustomAttribute(field_, typeof(System.Runtime.Serialization.EnumMemberAttribute)) 
                            as System.Runtime.Serialization.EnumMemberAttribute;
                        if (attribute != null)
                        {
                            return attribute.Value != null ? attribute.Value : name;
                        }
                    }

                    var converted = System.Convert.ToString(System.Convert.ChangeType(value, System.Enum.GetUnderlyingType(value.GetType()), cultureInfo));
                    return converted == null ? string.Empty : converted;
                }
            }
            else if (value is bool) 
            {
                return System.Convert.ToString((bool)value, cultureInfo).ToLowerInvariant();
            }
            else if (value is byte[])
            {
                return System.Convert.ToBase64String((byte[]) value);
            }
            else if (value is string[])
            {
                return string.Join(",", (string[])value);
            }
            else if (value.GetType().IsArray)
            {
                var valueArray = (System.Array)value;
                var valueTextArray = new string[valueArray.Length];
                for (var i = 0; i < valueArray.Length; i++)
                {
                    valueTextArray[i] = ConvertToString(valueArray.GetValue(i), cultureInfo);
                }
                return string.Join(",", valueTextArray);
            }

            var result = System.Convert.ToString(value, cultureInfo);
            return result == null ? "" : result;
        }
    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class GetCurrentResponse
    {

        [System.Text.Json.Serialization.JsonPropertyName("location")]
        public Location Location { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("current")]
        public Current Current { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class GetForecastResponse
    {

        [System.Text.Json.Serialization.JsonPropertyName("location")]
        public Location2 Location { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("current")]
        public Current2 Current { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("forecast")]
        public Forecast Forecast { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class GetHistoryResponse
    {

        [System.Text.Json.Serialization.JsonPropertyName("location")]
        public Location3 Location { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("forecast")]
        public Forecast2 Forecast { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class GetAlertsResponse
    {

        [System.Text.Json.Serialization.JsonPropertyName("location")]
        public Location4 Location { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("alerts")]
        public Alerts Alerts { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class GetCurrentRequest
    {

        [System.Text.Json.Serialization.JsonPropertyName("q")]
        public string Q { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("aqi")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<GetCurrentRequestAqi>))]
        public GetCurrentRequestAqi? Aqi { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("pollen")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<GetCurrentRequestPollen>))]
        public GetCurrentRequestPollen? Pollen { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("lang")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<GetCurrentRequestLang>))]
        public GetCurrentRequestLang? Lang { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("current_fields")]
        public string Current_fields { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class GetForecastRequest
    {

        [System.Text.Json.Serialization.JsonPropertyName("q")]
        public string Q { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("days")]
        public double? Days { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("dt")]
        public string Dt { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("unixdt")]
        public double? Unixdt { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("hour")]
        public double? Hour { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("alerts")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<GetForecastRequestAlerts>))]
        public GetForecastRequestAlerts? Alerts { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("aqi")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<GetForecastRequestAqi>))]
        public GetForecastRequestAqi? Aqi { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("pollen")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<GetForecastRequestPollen>))]
        public GetForecastRequestPollen? Pollen { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("tp")]
        public double? Tp { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("current_fields")]
        public string Current_fields { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("day_fields")]
        public string Day_fields { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("hour_fields")]
        public string Hour_fields { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("et0")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<GetForecastRequestEt0>))]
        public GetForecastRequestEt0? Et0 { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("lang")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<GetForecastRequestLang>))]
        public GetForecastRequestLang? Lang { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class GetHistoryRequest
    {

        [System.Text.Json.Serialization.JsonPropertyName("q")]
        public string Q { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("dt")]
        public string Dt { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("unixdt")]
        public double? Unixdt { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("end_dt")]
        public string End_dt { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("unixend_dt")]
        public double? Unixend_dt { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("hour")]
        public double? Hour { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("aqi")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<GetHistoryRequestAqi>))]
        public GetHistoryRequestAqi? Aqi { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("pollen")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<GetHistoryRequestPollen>))]
        public GetHistoryRequestPollen? Pollen { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("tp")]
        public double? Tp { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("current_fields")]
        public string Current_fields { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("day_fields")]
        public string Day_fields { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("hour_fields")]
        public string Hour_fields { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("solar")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<GetHistoryRequestSolar>))]
        public GetHistoryRequestSolar? Solar { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("et0")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<GetHistoryRequestEt0>))]
        public GetHistoryRequestEt0? Et0 { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("wind100mph")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<GetHistoryRequestWind100mph>))]
        public GetHistoryRequestWind100mph? Wind100mph { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("wind100kph")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<GetHistoryRequestWind100kph>))]
        public GetHistoryRequestWind100kph? Wind100kph { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("lang")]
        [System.Text.Json.Serialization.JsonConverter(typeof(System.Text.Json.Serialization.JsonStringEnumConverter<GetHistoryRequestLang>))]
        public GetHistoryRequestLang? Lang { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class GetAlertsRequest
    {

        [System.Text.Json.Serialization.JsonPropertyName("q")]
        public string Q { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Location
    {

        [System.Text.Json.Serialization.JsonPropertyName("name")]
        public string Name { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("region")]
        public string Region { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("country")]
        public string Country { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("lat")]
        public double Lat { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("lon")]
        public double Lon { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("tz_id")]
        public string Tz_id { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("localtime_epoch")]
        public double Localtime_epoch { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("localtime")]
        public string Localtime { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Current
    {

        [System.Text.Json.Serialization.JsonPropertyName("last_updated_epoch")]
        public double Last_updated_epoch { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("last_updated")]
        public string Last_updated { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("temp_c")]
        public double Temp_c { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("temp_f")]
        public double Temp_f { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("is_day")]
        public int Is_day { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("condition")]
        public Condition Condition { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("wind_mph")]
        public double Wind_mph { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("wind_kph")]
        public double Wind_kph { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("wind_degree")]
        public int Wind_degree { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("wind_dir")]
        public string Wind_dir { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("pressure_mb")]
        public double Pressure_mb { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("pressure_in")]
        public double Pressure_in { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("precip_mm")]
        public double Precip_mm { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("precip_in")]
        public double Precip_in { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("humidity")]
        public int Humidity { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("cloud")]
        public int Cloud { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("feelslike_c")]
        public double Feelslike_c { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("feelslike_f")]
        public double Feelslike_f { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("windchill_c")]
        public double Windchill_c { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("windchill_f")]
        public double Windchill_f { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("heatindex_c")]
        public double Heatindex_c { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("heatindex_f")]
        public double Heatindex_f { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("dewpoint_c")]
        public double Dewpoint_c { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("dewpoint_f")]
        public double Dewpoint_f { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("vis_km")]
        public double Vis_km { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("vis_miles")]
        public double Vis_miles { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("uv")]
        public double Uv { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("gust_mph")]
        public double Gust_mph { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("gust_kph")]
        public double Gust_kph { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("short_rad")]
        public double Short_rad { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("diff_rad")]
        public double Diff_rad { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("dni")]
        public double Dni { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("gti")]
        public double Gti { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Location2
    {

        [System.Text.Json.Serialization.JsonPropertyName("name")]
        public string Name { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("region")]
        public string Region { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("country")]
        public string Country { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("lat")]
        public double Lat { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("lon")]
        public double Lon { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("tz_id")]
        public string Tz_id { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("localtime_epoch")]
        public double Localtime_epoch { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("localtime")]
        public string Localtime { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Current2
    {

        [System.Text.Json.Serialization.JsonPropertyName("last_updated_epoch")]
        public double Last_updated_epoch { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("last_updated")]
        public string Last_updated { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("temp_c")]
        public double Temp_c { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("temp_f")]
        public double Temp_f { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("is_day")]
        public int Is_day { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("condition")]
        public Condition2 Condition { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("wind_mph")]
        public double Wind_mph { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("wind_kph")]
        public double Wind_kph { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("wind_degree")]
        public int Wind_degree { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("wind_dir")]
        public string Wind_dir { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("pressure_mb")]
        public double Pressure_mb { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("pressure_in")]
        public double Pressure_in { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("precip_mm")]
        public double Precip_mm { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("precip_in")]
        public double Precip_in { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("humidity")]
        public int Humidity { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("cloud")]
        public int Cloud { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("feelslike_c")]
        public double Feelslike_c { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("feelslike_f")]
        public double Feelslike_f { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("windchill_c")]
        public double Windchill_c { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("windchill_f")]
        public double Windchill_f { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("heatindex_c")]
        public double Heatindex_c { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("heatindex_f")]
        public double Heatindex_f { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("dewpoint_c")]
        public double Dewpoint_c { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("dewpoint_f")]
        public double Dewpoint_f { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("vis_km")]
        public double Vis_km { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("vis_miles")]
        public double Vis_miles { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("uv")]
        public double Uv { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("gust_mph")]
        public double Gust_mph { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("gust_kph")]
        public double Gust_kph { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("short_rad")]
        public double Short_rad { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("diff_rad")]
        public double Diff_rad { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("dni")]
        public double Dni { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("gti")]
        public double Gti { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Forecast
    {

        [System.Text.Json.Serialization.JsonPropertyName("forecastday")]
        public System.Collections.Generic.ICollection<Forecastday> Forecastday { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Location3
    {

        [System.Text.Json.Serialization.JsonPropertyName("name")]
        public string Name { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("region")]
        public string Region { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("country")]
        public string Country { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("lat")]
        public double Lat { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("lon")]
        public double Lon { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("tz_id")]
        public string Tz_id { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("localtime_epoch")]
        public double Localtime_epoch { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("localtime")]
        public string Localtime { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Forecast2
    {

        [System.Text.Json.Serialization.JsonPropertyName("forecastday")]
        public System.Collections.Generic.ICollection<Forecastday2> Forecastday { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Location4
    {

        [System.Text.Json.Serialization.JsonPropertyName("name")]
        public string Name { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("region")]
        public string Region { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("country")]
        public string Country { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("lat")]
        public double Lat { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("lon")]
        public double Lon { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("tz_id")]
        public string Tz_id { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("localtime_epoch")]
        public double Localtime_epoch { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("localtime")]
        public string Localtime { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Alerts
    {

        [System.Text.Json.Serialization.JsonPropertyName("alert")]
        public System.Collections.Generic.ICollection<Alert> Alert { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum GetCurrentRequestAqi
    {

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"yes")]
        Yes = 0,

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"no")]
        No = 1,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum GetCurrentRequestPollen
    {

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"yes")]
        Yes = 0,

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"no")]
        No = 1,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum GetCurrentRequestLang
    {

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"ru")]
        Ru = 0,

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"en")]
        En = 1,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum GetForecastRequestAlerts
    {

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"yes")]
        Yes = 0,

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"no")]
        No = 1,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum GetForecastRequestAqi
    {

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"yes")]
        Yes = 0,

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"no")]
        No = 1,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum GetForecastRequestPollen
    {

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"yes")]
        Yes = 0,

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"no")]
        No = 1,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum GetForecastRequestEt0
    {

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"yes")]
        Yes = 0,

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"no")]
        No = 1,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum GetForecastRequestLang
    {

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"ru")]
        Ru = 0,

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"en")]
        En = 1,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum GetHistoryRequestAqi
    {

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"yes")]
        Yes = 0,

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"no")]
        No = 1,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum GetHistoryRequestPollen
    {

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"yes")]
        Yes = 0,

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"no")]
        No = 1,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum GetHistoryRequestSolar
    {

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"yes")]
        Yes = 0,

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"no")]
        No = 1,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum GetHistoryRequestEt0
    {

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"yes")]
        Yes = 0,

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"no")]
        No = 1,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum GetHistoryRequestWind100mph
    {

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"yes")]
        Yes = 0,

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"no")]
        No = 1,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum GetHistoryRequestWind100kph
    {

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"yes")]
        Yes = 0,

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"no")]
        No = 1,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum GetHistoryRequestLang
    {

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"ru")]
        Ru = 0,

        [System.Text.Json.Serialization.JsonStringEnumMemberName(@"en")]
        En = 1,

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Condition
    {

        [System.Text.Json.Serialization.JsonPropertyName("text")]
        public string Text { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("icon")]
        public string Icon { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("code")]
        public int Code { get; set; }

        private System.Collections.Generic.IDictionary<string, object> _additionalProperties;

        [System.Text.Json.Serialization.JsonExtensionData]
        public System.Collections.Generic.IDictionary<string, object> AdditionalProperties
        {
            get { return _additionalProperties ?? (_additionalProperties = new System.Collections.Generic.Dictionary<string, object>()); }
            set { _additionalProperties = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Condition2
    {

        [System.Text.Json.Serialization.JsonPropertyName("text")]
        public string Text { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("icon")]
        public string Icon { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("code")]
        public int Code { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Forecastday
    {

        [System.Text.Json.Serialization.JsonPropertyName("date")]
        [System.Text.Json.Serialization.JsonConverter(typeof(DateFormatConverter))]
        public System.DateTime Date { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("date_epoch")]
        public double Date_epoch { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("day")]
        public Day Day { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("astro")]
        public Astro Astro { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("hour")]
        public System.Collections.Generic.ICollection<Hour> Hour { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Forecastday2
    {

        [System.Text.Json.Serialization.JsonPropertyName("date")]
        [System.Text.Json.Serialization.JsonConverter(typeof(DateFormatConverter))]
        public System.DateTime Date { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("date_epoch")]
        public double Date_epoch { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("day")]
        public Day2 Day { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("astro")]
        public Astro2 Astro { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("hour")]
        public System.Collections.Generic.ICollection<Hour2> Hour { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Alert
    {

        [System.Text.Json.Serialization.JsonPropertyName("identifier")]
        public string Identifier { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("headline")]
        public string Headline { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("msgtype")]
        public string Msgtype { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("severity")]
        public string Severity { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("urgency")]
        public string Urgency { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("areas")]
        public string Areas { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("category")]
        public string Category { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("certainty")]
        public string Certainty { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("event")]
        public string Event { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("note")]
        public string Note { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("effective")]
        public System.DateTime Effective { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("expires")]
        public System.DateTime Expires { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("desc")]
        public string Desc { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("instruction")]
        public string Instruction { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Day
    {

        [System.Text.Json.Serialization.JsonPropertyName("maxtemp_c")]
        public double Maxtemp_c { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("maxtemp_f")]
        public double Maxtemp_f { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("mintemp_c")]
        public double Mintemp_c { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("mintemp_f")]
        public double Mintemp_f { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("avgtemp_c")]
        public double Avgtemp_c { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("avgtemp_f")]
        public double Avgtemp_f { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("maxwind_mph")]
        public double Maxwind_mph { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("maxwind_kph")]
        public double Maxwind_kph { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("totalprecip_mm")]
        public double Totalprecip_mm { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("totalprecip_in")]
        public double Totalprecip_in { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("totalsnow_cm")]
        public double Totalsnow_cm { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("avgvis_km")]
        public double Avgvis_km { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("avgvis_miles")]
        public double Avgvis_miles { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("avghumidity")]
        public int Avghumidity { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("daily_will_it_rain")]
        public int Daily_will_it_rain { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("daily_chance_of_rain")]
        public int Daily_chance_of_rain { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("daily_will_it_snow")]
        public int Daily_will_it_snow { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("daily_chance_of_snow")]
        public int Daily_chance_of_snow { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("condition")]
        public Condition3 Condition { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("uv")]
        public double Uv { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Astro
    {

        [System.Text.Json.Serialization.JsonPropertyName("sunrise")]
        public string Sunrise { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("sunset")]
        public string Sunset { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("moonrise")]
        public string Moonrise { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("moonset")]
        public string Moonset { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("moon_phase")]
        public string Moon_phase { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("moon_illumination")]
        public double Moon_illumination { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("is_moon_up")]
        public int Is_moon_up { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("is_sun_up")]
        public int Is_sun_up { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Hour
    {

        [System.Text.Json.Serialization.JsonPropertyName("time_epoch")]
        public double Time_epoch { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("time")]
        public string Time { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("temp_c")]
        public double Temp_c { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("temp_f")]
        public double Temp_f { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("is_day")]
        public int Is_day { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("condition")]
        public Condition4 Condition { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("wind_mph")]
        public double Wind_mph { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("wind_kph")]
        public double Wind_kph { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("wind_degree")]
        public int Wind_degree { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("wind_dir")]
        public string Wind_dir { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("pressure_mb")]
        public double Pressure_mb { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("pressure_in")]
        public double Pressure_in { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("precip_mm")]
        public double Precip_mm { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("precip_in")]
        public double Precip_in { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("snow_cm")]
        public double Snow_cm { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("humidity")]
        public int Humidity { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("cloud")]
        public int Cloud { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("feelslike_c")]
        public double Feelslike_c { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("feelslike_f")]
        public double Feelslike_f { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("windchill_c")]
        public double Windchill_c { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("windchill_f")]
        public double Windchill_f { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("heatindex_c")]
        public double Heatindex_c { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("heatindex_f")]
        public double Heatindex_f { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("dewpoint_c")]
        public double Dewpoint_c { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("dewpoint_f")]
        public double Dewpoint_f { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("will_it_rain")]
        public int Will_it_rain { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("chance_of_rain")]
        public int Chance_of_rain { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("will_it_snow")]
        public int Will_it_snow { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("chance_of_snow")]
        public int Chance_of_snow { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("vis_km")]
        public double Vis_km { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("vis_miles")]
        public double Vis_miles { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("gust_mph")]
        public double Gust_mph { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("gust_kph")]
        public double Gust_kph { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("uv")]
        public double Uv { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("short_rad")]
        public double Short_rad { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("diff_rad")]
        public double Diff_rad { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("dni")]
        public double Dni { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("gti")]
        public double Gti { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Day2
    {

        [System.Text.Json.Serialization.JsonPropertyName("maxtemp_c")]
        public double Maxtemp_c { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("maxtemp_f")]
        public double Maxtemp_f { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("mintemp_c")]
        public double Mintemp_c { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("mintemp_f")]
        public double Mintemp_f { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("avgtemp_c")]
        public double Avgtemp_c { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("avgtemp_f")]
        public double Avgtemp_f { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("maxwind_mph")]
        public double Maxwind_mph { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("maxwind_kph")]
        public double Maxwind_kph { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("totalprecip_mm")]
        public double Totalprecip_mm { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("totalprecip_in")]
        public double Totalprecip_in { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("totalsnow_cm")]
        public double Totalsnow_cm { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("avgvis_km")]
        public double Avgvis_km { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("avgvis_miles")]
        public double Avgvis_miles { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("avghumidity")]
        public int Avghumidity { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("daily_will_it_rain")]
        public int Daily_will_it_rain { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("daily_chance_of_rain")]
        public int Daily_chance_of_rain { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("daily_will_it_snow")]
        public int Daily_will_it_snow { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("daily_chance_of_snow")]
        public int Daily_chance_of_snow { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("condition")]
        public Condition5 Condition { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("uv")]
        public double Uv { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Astro2
    {

        [System.Text.Json.Serialization.JsonPropertyName("sunrise")]
        public string Sunrise { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("sunset")]
        public string Sunset { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("moonrise")]
        public string Moonrise { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("moonset")]
        public string Moonset { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("moon_phase")]
        public string Moon_phase { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("moon_illumination")]
        public double Moon_illumination { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Hour2
    {

        [System.Text.Json.Serialization.JsonPropertyName("time_epoch")]
        public double Time_epoch { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("time")]
        public string Time { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("temp_c")]
        public double Temp_c { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("temp_f")]
        public double Temp_f { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("is_day")]
        public int Is_day { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("condition")]
        public Condition6 Condition { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("wind_mph")]
        public double Wind_mph { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("wind_kph")]
        public double Wind_kph { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("wind_degree")]
        public int Wind_degree { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("wind_dir")]
        public string Wind_dir { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("pressure_mb")]
        public double Pressure_mb { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("pressure_in")]
        public double Pressure_in { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("precip_mm")]
        public double Precip_mm { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("precip_in")]
        public double Precip_in { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("snow_cm")]
        public double Snow_cm { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("humidity")]
        public int Humidity { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("cloud")]
        public int Cloud { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("feelslike_c")]
        public double Feelslike_c { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("feelslike_f")]
        public double Feelslike_f { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("windchill_c")]
        public double Windchill_c { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("windchill_f")]
        public double Windchill_f { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("heatindex_c")]
        public double Heatindex_c { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("heatindex_f")]
        public double Heatindex_f { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("dewpoint_c")]
        public double Dewpoint_c { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("dewpoint_f")]
        public double Dewpoint_f { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("will_it_rain")]
        public int Will_it_rain { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("chance_of_rain")]
        public int Chance_of_rain { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("will_it_snow")]
        public int Will_it_snow { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("chance_of_snow")]
        public int Chance_of_snow { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("vis_km")]
        public double Vis_km { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("vis_miles")]
        public double Vis_miles { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("gust_mph")]
        public double Gust_mph { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("gust_kph")]
        public double Gust_kph { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("uv")]
        public double Uv { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Condition3
    {

        [System.Text.Json.Serialization.JsonPropertyName("text")]
        public string Text { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("icon")]
        public string Icon { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("code")]
        public int Code { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Condition4
    {

        [System.Text.Json.Serialization.JsonPropertyName("text")]
        public string Text { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("icon")]
        public string Icon { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("code")]
        public int Code { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Condition5
    {

        [System.Text.Json.Serialization.JsonPropertyName("text")]
        public string Text { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("icon")]
        public string Icon { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("code")]
        public int Code { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class Condition6
    {

        [System.Text.Json.Serialization.JsonPropertyName("text")]
        public string Text { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("icon")]
        public string Icon { get; set; }

        [System.Text.Json.Serialization.JsonPropertyName("code")]
        public int Code { get; set; }

    }

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    internal class DateFormatConverter : System.Text.Json.Serialization.JsonConverter<System.DateTime>
    {
        public override System.DateTime Read(ref System.Text.Json.Utf8JsonReader reader, System.Type typeToConvert, System.Text.Json.JsonSerializerOptions options)
        {
            var dateTime = reader.GetString();
            if (dateTime == null)
            {
                throw new System.Text.Json.JsonException("Unexpected JsonTokenType.Null");
            }

            return System.DateTime.Parse(dateTime);
        }

        public override void Write(System.Text.Json.Utf8JsonWriter writer, System.DateTime value, System.Text.Json.JsonSerializerOptions options)
        {
            writer.WriteStringValue(value.ToString("yyyy-MM-dd"));
        }
    }



    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class WeatherApiException : System.Exception
    {
        public int StatusCode { get; private set; }

        public string Response { get; private set; }

        public System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IEnumerable<string>> Headers { get; private set; }

        public WeatherApiException(string message, int statusCode, string response, System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IEnumerable<string>> headers, System.Exception innerException)
            : base(message + "\n\nStatus: " + statusCode + "\nResponse: \n" + ((response == null) ? "(null)" : response.Substring(0, response.Length >= 512 ? 512 : response.Length)), innerException)
        {
            StatusCode = statusCode;
            Response = response;
            Headers = headers;
        }

        public override string ToString()
        {
            return string.Format("HTTP Response: \n\n{0}\n\n{1}", Response, base.ToString());
        }
    }

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.6.3.0 (NJsonSchema v11.5.2.0 (Newtonsoft.Json v13.0.0.0))")]
    public partial class WeatherApiException<TResult> : WeatherApiException
    {
        public TResult Result { get; private set; }

        public WeatherApiException(string message, int statusCode, string response, System.Collections.Generic.IReadOnlyDictionary<string, System.Collections.Generic.IEnumerable<string>> headers, TResult result, System.Exception innerException)
            : base(message, statusCode, response, headers, innerException)
        {
            Result = result;
        }
    }

}

#pragma warning restore  108
#pragma warning restore  114
#pragma warning restore  472
#pragma warning restore  612
#pragma warning restore  649
#pragma warning restore 1573
#pragma warning restore 1591
#pragma warning restore 8073
#pragma warning restore 3016
#pragma warning restore 8600
#pragma warning restore 8602
#pragma warning restore 8603
#pragma warning restore 8604
#pragma warning restore 8625
#pragma warning restore 8765